version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  nodejs:
    build:
      context: .
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    command: ts-node-dev --respawn --transpile-only --poll app/server.ts

volumes:
  db_data:
  node_modules_volume:

networks:
  app-network:
    driver: bridge
